# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - name: Checkout Repo
      uses: actions/checkout@v2
      
    - name: Setup Node
      uses: actions/setup-node@v1
      with:
        node-version: '10.x'
        
    - name: Update publish branch
      run: |
        git fetch --all
        git checkout -b tmp origin/master
        git merge -s ours origin/publish
        git checkout publish
        git merge --ff-only tmp
        git branch -D tmp
      
    - name: NPM Install and Build
      id: build
      run: |
        npm install
        npm run build
        mv build publish
        echo "::set-output name=changestatus::$(git status)" 
        echo "" 
    - name: Add Publish Directory as Artifact
      id: artifact
      uses: actions/upload-artifact@v2
      with:
        name: publishDirectory
        path: publish
    - name: Push to publish branch
      id: publish
      if: contains(steps.build.outputs.changestatus, 'Changes not staged for commit')
      run: |
        git config --global user.name 'Automatic Publisher'
        git config --global user.email 'coleh2@users.noreply.github.com'
        
        git add .
        git commit -m "Automatic Publish"
        
        git push --set-upstream origin publish
