# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - name: Checkout Repo
      uses: actions/checkout@v2
      
    - name: Setup Node
      uses: actions/setup-node@v1
      with:
        node-version: '10.x'
      
    - name: npm install and build
      run: |
        cd "$GITHUB_WORKSPACE"
        npm install
        npm run build
        
    - name: push to publish branch
      run: |
        git config --global user.name 'Automatic Publisher'
        git config --global user.email 'coleh2@users.noreply.github.com'
        git add .
        git commit -am "Automatic Publish"
        git push origin HEAD:publish
